// ui/src/stories/components/inputs/textarea/Index.tsx
import { PropType, defineComponent } from 'vue';
import { BCMSTextAreaInput } from '../../../../components';
import { action } from '@storybook/addon-actions';
import React from 'react';

const component = defineComponent({
  props: {
    value: Number,
    class: String,
    placeholder: String,
    label: String,
    invalidText: String,
    disabled: Boolean,
    helperText: String,
    // minHeight: {
    //   type: Number,
    //   default: 44,
    // },
    format: Function as PropType<(value: string) => string>,
  },
  setup(props) {
    return () => {
      return (
        <BCMSTextAreaInput
          class={props.class}
          value={props.value}
          placeholder={props.placeholder}
          label={props.label}
          invalid-text={props.invalidText}
          disabled={props.disabled}
          helper-text={props.helperText}
          // min-height={props.minHeight}
          onInput={action('input')}
        />
      );
    };
  },
});

export default component;

// src/frontend/components/global/text-area.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export { className as class };
  export let style = '';
  export let value = '';
  export let placeholder = '';
  export let labelText;
  export let helperText;
  export let invalidText;
  export let invalid;
  export let cols;
  export let rows;
  export let disabled = false;

  const dispatch = createEventDispatcher();
  let className = '';
</script>

<div class="{className} input-wrapper">
  {#if labelText}
    <label class="label">{labelText}</label>
    {#if helperText}
      <div class="helper-text">{helperText}</div>
    {/if}
  {/if}
  {#if invalid && invalid === true}
    <div class="invalid-text">
      <span class="fas fa-exclamation icon" />
      {invalidText}
    </div>
  {/if}
  <textarea
    {style}
    {disabled}
    {placeholder}
    {cols}
    {rows}
    value={`${value}`}
    on:keyup={event => {
      dispatch('input', event.target.value);
    }} />
</div>
